// This file was generated by lezer-generator. You probably shouldn't edit it.
const {Parser} = require("lezer")
exports.parser = Parser.deserialize({
  version: 12,
  states: "$zOVQPOOOOQO'#C`'#C`O_QPO'#C_OYQPO'#C^QOQPOOOdQPO,58yOOQO,58x,58xOOQO'#Ca'#CaOOQO'#Cb'#CbOxQPO'#CoOOQO'#Co'#CoOdQPO'#CoO!pQPO'#CdO#RQPO'#CgOOQO'#Cv'#CvOOQO'#Cg'#CgO#vQPO1G.eO$QQPO1G.eO$VQPO,59ZO$[QPO,59ZOOQO,59O,59OOOQO,59P,59POOQO,59Q,59QO$fQPO,58}OOQO-E6e-E6eOdQPO'#ChOOQO7+$P7+$POOQO1G.u1G.uOOQO-E6f-E6fO$qQPO,59S",
  stateData: "%O~O_OS~O`ROaPO~ObTO~OaPOdVOeVOfWOgZOk[O~ObTOacXdcXecXfcXgcXicXkcXlcXmcXncXhcX~OaPOdVOeVOfWOgZO~OleOmfOaZXdZXeZXfZXgZXiZXkZXnZXhZX~OiiOnjO~PdOnjO~OhkO~OhkOiiO~PdOiiOnVahVa~Oi[an[ah[a~PdO",
  goto: "#ekPPlo!Ouu!]!c!c!c!k!yPPPPPP#QPPPPPP#]RSOQSOQUR_YTZ[`cimSQOR_XTZ[`cimQaTRbZ]^TZ`cimQ`TQcZUh`cmRmiSg`cRlg[]TZ`cimRd[]_TZ`cim",
  nodeNames: "⚠ Grammar Top DefExpression Identifier LiteralString LiteralRegexp ChoiceOp NegateOp PlusOp AstOp",
  maxTerm: 30,
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: "-^~RcXY!^YZ!^]^!^pq!^qr!crs&Otu'Vwx*kxy+oyz+tz{+y{|,O!b!c,T!c!},l#R#S,l#T#o,l#o#p,}#p#q-S#q#r-X~!cO_~~!hPk~!}#O!k~!nRp#O!w#O#P$v#Q~!w~!zSp#O!w#O#P#W#P#Q$q#Q~!w~#Zapr!wrs!ws#O!w#O#P#W#P#Q$`#Q#U!w#U#V!w#V#Y!w#Y#Z!w#Z#b!w#b#c!w#c#f!w#f#g!w#g#h!w#h#i!w#i#j!w#j~!w~$eSf~p#O!w#O#P#W#P#Q$q#Q~!w~$vOf~~$yapr!wrs!ws#O!w#O#P#W#P#Q$`#Q#U!w#U#V!w#V#Y!w#Y#Z!w#Z#b!w#b#c!w#c#f!w#f#g!w#g#h!w#h#i!w#i#j!w#j~!w~&RUpq&Oqr&Ors&es#O&O#O#P&j#P~&O~&jOd~~&mWrs&O#O#P&O#U#V&O#Y#Z&O#b#c&O#f#g&O#h#i&O#i#j&O~'YP!}#O']~'`Rp#O'i#O#P)c#Q~'i~'lSp#O'i#O#P'x#P#Q$q#Q~'i~'{apr'irs'is#O'i#O#P'x#P#Q)Q#Q#U'i#U#V'i#V#Y'i#Y#Z'i#Z#b'i#b#c'i#c#f'i#f#g'i#g#h'i#h#i'i#i#j'i#j~'i~)VSf~p#O'i#O#P'x#P#Q$q#Q~'i~)fapr'irs'is#O'i#O#P'x#P#Q)Q#Q#U'i#U#V'i#V#Y'i#Y#Z'i#Z#b'i#b#c'i#c#f'i#f#g'i#g#h'i#h#i'i#i#j'i#j~'i~*nTpw*kwx*}x#O*k#O#P+S#P~*k~+SOe~~+VWrs*k#O#P*k#U#V*k#Y#Z*k#b#c*k#f#g*k#h#i*k#i#j*k~+tOg~~+yOh~~,OOm~~,TOl~~,WP#h#i,Z~,^P#c#d,a~,dP#d#e,g~,lO`~~,qSa~!Q![,l!c!},l#R#S,l#T#o,l~-SOb~~-XOi~~-^On~",
  tokenizers: [0],
  topRules: {"Grammar":[0,1]},
  tokenPrec: 0
})
