// This file was generated by lezer-generator. You probably shouldn't edit it.
const {Parser} = require("lezer")
exports.parser = Parser.deserialize({
  version: 12,
  states: ")YOVQPOOOOQO'#C`'#C`OhQPO'#C_OmQPO'#C^OrQPO'#ChOwQPO'#CkO|QPO'#CpQOQPOOO!RQPO,58yOOQO,58x,58xO!jQPO,59SOmQPO,59VOmQPO,59[OOQO'#Cb'#CbOOQO'#Cc'#CcO!qQPO'#C|OOQO'#C|'#C|O!RQPO'#C|O#lQPO'#CeO$QQPO'#CqOOQO'#DS'#DSOOQO'#Cq'#CqO$xQPO'#C{OOQO'#C{'#C{O%VQPO1G.eOOQO'#Ci'#CiO%[QPO1G.nO%dQPO1G.nO%iQPO'#ClOOQO'#D['#D[O%zQPO1G.qO&SQPO1G.vO&XQPO,59hOOQO,59P,59POOQO,59Q,59QOOQO,59R,59ROOQO-E6o-E6oO&^QPO,58{O!RQPO'#CrOOQO7+$P7+$PO&iQPO7+$YO&qQPO7+$YOOQO,59X,59XOOQO,59Y,59YOOQO,59Z,59ZOmQPO'#CtO&yQPO7+$]OOQO7+$]7+$]OOQO7+$b7+$bOOQO1G/S1G/SOOQO-E6p-E6pO'RQPO,59^OOQO'#Cs'#CsO'`QPO'#CjO'hQPO<<GtO&iQPO<<GtOOQO,59`,59`OOQO-E6r-E6rOOQO<<Gw<<GwOOQO-E6q-E6qOOQOAN=`AN=`O'mQPOAN=`OOQOG22zG22z",
  stateData: "'r~OkOS~OlROmPO|SO}TO!TUO~OnWO~OmPO~OnYO~OnZO~On[O~OW`OmPOq]Or]Os^OtaOwbO~O{jO~P!ROnWOWpXmpXqpXrpXspXtpXwpXxpXypXzpX{pXupX~OW`OmPOq]Or]Os^OtaO~OxrOysOWeXmeXqeXreXseXteXweXzeX{eXueX~OzvO{oXuoX~P!RO{wO~OnxOi[i~O{yO~O!PzO!Q{O!R|O{`X!S`X~O{!PO!S}O~O{!QO~Ou!RO~OzvO{TauTa~OmPO{^P~On!XOi[q~O{![O!S}O~Ozfa{faufa~P!ROmPO{^X~O{!^O~O{!`O~O",
  goto: "%X!PPP!Q!T!h#P#U#UP#_#_#_!Q#g#j!Q#p#p#p#p!Q#t$Q$W$_PPPPPP$e$nPPPPP$yPPPPPPP%RRVOQVOQXRUgWYaQo[V!Ux!V!X[QOR[x!V!XU_WYaW`bfv!TTlZ}VgWYa_`WYabfv!T]dWYafv!TRkYQ!WxR!_!XTmZ}UfWYaStf!TR!TvQufR!SuS!Vx!XR!]!VQ!OnR!Z!OQhWQiYRpa[cWYafv!TRqb]eWYafv!TQnZR!Y}",
  nodeNames: "⚠ Grammar Top Rule Identifier ChoiceOp LiteralString LiteralRegexp Any NegateOp PlusOp AstOp Skip MainSkip ScopedSkip Precedence PrecedenceItem PrecedenceItemCut PrecedenceItemLeft PrecedenceItemRight Tokens",
  maxTerm: 51,
  skippedNodes: [0],
  repeatNodeCount: 4,
  tokenData: "1v~RdXY!aYZ!a]^!apq!aqr!frs&Rtu'Ywx*nxy+ryz+wz{+|{|,R|},W!b!c,]!c!}0|#R#S1b#T#o0|#o#p1g#p#q1l#q#r1q~!fOk~~!kPw~!}#O!n~!qRp#O!z#O#P$y#Q~!z~!}Sp#O!z#O#P#Z#P#Q$t#Q~!z~#^apr!zrs!zs#O!z#O#P#Z#P#Q$c#Q#U!z#U#V!z#V#Y!z#Y#Z!z#Z#b!z#b#c!z#c#f!z#f#g!z#g#h!z#h#i!z#i#j!z#j~!z~$hSs~p#O!z#O#P#Z#P#Q$t#Q~!z~$yOs~~$|apr!zrs!zs#O!z#O#P#Z#P#Q$c#Q#U!z#U#V!z#V#Y!z#Y#Z!z#Z#b!z#b#c!z#c#f!z#f#g!z#g#h!z#h#i!z#i#j!z#j~!z~&UUpq&Rqr&Rrs&hs#O&R#O#P&m#P~&R~&mOq~~&pWrs&R#O#P&R#U#V&R#Y#Z&R#b#c&R#f#g&R#h#i&R#i#j&R~']P!}#O'`~'cRp#O'l#O#P)f#Q~'l~'oSp#O'l#O#P'{#P#Q$t#Q~'l~(Oapr'lrs'ls#O'l#O#P'{#P#Q)T#Q#U'l#U#V'l#V#Y'l#Y#Z'l#Z#b'l#b#c'l#c#f'l#f#g'l#g#h'l#h#i'l#i#j'l#j~'l~)YSs~p#O'l#O#P'{#P#Q$t#Q~'l~)iapr'lrs'ls#O'l#O#P'{#P#Q)T#Q#U'l#U#V'l#V#Y'l#Y#Z'l#Z#b'l#b#c'l#c#f'l#f#g'l#g#h'l#h#i'l#i#j'l#j~'l~*qTpw*nwx+Qx#O*n#O#P+V#P~*n~+VOr~~+YWrs*n#O#P*n#U#V*n#Y#Z*n#b#c*n#f#g*n#h#i*n#i#j*n~+wOt~~+|Ou~~,ROy~~,WOx~~,]O!S~~,`U#V#W,r#`#a-T#d#e-l#f#g.y#g#h/h#h#i0P~,uP#i#j,x~,{P#h#i-O~-TO!P~~-WP#X#Y-Z~-^P#Y#Z-a~-dP#h#i-g~-lO!Q~~-oP#f#g-r~-uP#X#Y-x~-{P#V#W.O~.RP#X#Y.U~.XP#W#X.[~._P#X#Y.b~.eP#b#c.h~.kP#V#W.n~.qP#X#Y.t~.yO}~~.|P#]#^/P~/SP#Z#[/V~/YP#[#]/]~/`P#h#i/c~/hO!R~~/kP#_#`/n~/qP#]#^/t~/wP#d#e/z~0PO|~~0SP#c#d0V~0YQ#_#`0`#d#e0w~0cP#X#Y0f~0iP#b#c0l~0oP#g#h0r~0wO!T~~0|Ol~~1RTm~!O!P0|!Q![0|!c!}0|#R#S0|#T#o0|~1gOW~~1lOn~~1qOz~~1vO{~",
  tokenizers: [0],
  topRules: {"Grammar":[0,1]},
  tokenPrec: 0
})
