// This file was generated by lezer-generator. You probably shouldn't edit it.
module.exports = {
  Top: 2,
  DefExpression: 3,
  Identifier: 4,
  LiteralString: 5,
  LiteralRegexp: 6,
  ChoiceOp: 7,
  NegateOp: 8,
  PlusOp: 9,
  AstOp: 10
}