// This file was generated by lezer-generator. You probably shouldn't edit it.
module.exports = {
  Top: 2,
  Rule: 3,
  Identifier: 4,
  ChoiceOp: 5,
  LiteralString: 6,
  LiteralRegexp: 7,
  NegateOp: 8,
  PlusOp: 9,
  AstOp: 10,
  Skip: 11,
  MainSkip: 12,
  ScopedSkip: 13,
  Precedence: 14,
  PrecedenceItem: 15,
  CutOp: 16,
  LeftOp: 17,
  RightOp: 18
}